### ISSUE TITLE
大佬  可以教教我怎么把这个项目完整的跑起来吗？

### ISSUE THREAD

**Issue by pear1958** [KivenGood/UAV-simulation#1]
有偿

**Comment by KivenGood** [comment]
https://gitee.com/KivenGood/uav-simulation
按步骤基本可以跑起来了，如果还不行，或者报错，可以再联系我。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KivenGood/UAV-simulation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月9日(星期五) 上午10:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KivenGood/UAV-simulation] 大佬  可以教教我怎么把这个项目完整的跑起来吗？ (#1)





 
有偿

**Comment by pear1958** [comment]
var sourceConfig = {
    // 资源配置
    mapImagesSource: 'http://localhost:8081/hainanimage/tiles',//瓦片切成地形的图片格式路径
    mapImagesSourceType: 'png',//一般为png或者jpg
    mapTerrainSource: "http://localhost:8081/hainan",//瓦片资源路径
    planeMode: 'http://localhost:8081/models/ch.gltf',
};
我不知道 这里 的 离线地图地址 要怎么配置

我现在的执行步骤是
1.拉取代码
2.npm install & npm start  & 访问localhost: 8081 点击get start按钮  访问飞机页面
页面会报很多404  求解

**Comment by KivenGood** [comment]
LZ11322
加我微信看一下；





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KivenGood/UAV-simulation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月9日(星期五) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KivenGood/UAV-simulation] 大佬  可以教教我怎么把这个项目完整的跑起来吗？ (#1)





 
var sourceConfig = { // 资源配置 mapImagesSource: 'http://localhost:8081/hainanimage/tiles',//瓦片切成地形的图片格式路径 mapImagesSourceType: 'png',//一般为png或者jpg mapTerrainSource: "http://localhost:8081/hainan",//瓦片资源路径 planeMode: 'http://localhost:8081/models/ch.gltf', };
 我不知道 这里 的 离线地图地址 要怎么配置
 
我现在的执行步骤是
 1.拉取代码
 2.npm install &amp; npm start  &amp; 访问localhost: 8081 点击get start按钮  访问飞机页面
 页面会报很多404  求解

**Comment by KivenGood** [comment]
已解决。
